// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gttbsnijvghilrhrclbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dGJzbmlqdmdoaWxyaHJjbGJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MjQxMDEsImV4cCI6MjA3NjIwMDEwMX0.bZzIfa1sthPbrPDLN0SqHWmdyQER4F7PhwKzkjf_zPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});