// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvkawsgrjnbdufdgzwwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12a2F3c2dyam5iZHVmZGd6d3dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzkzMDAsImV4cCI6MjA2OTgxNTMwMH0.Eg0waCz0jG98Q8YJNNB7kpHUyI3m4bFb1SAOG1ne2Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});